# This file was generated by GoReleaser. DO NOT EDIT.
cask "hone" do
  name "hone"
  desc "AI-powered code review tool"
  homepage "https://github.com/thirdlf03/hone"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hone"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/hone/releases/download/v#{version}/hone_#{version}_Darwin_x86_64.tar.gz"
      sha256 "3e71332ec4491a515ef17fd05e68be46a917134277c447168f6247a620aacbe6"
    end
    on_arm do
      url "https://github.com/thirdlf03/hone/releases/download/v#{version}/hone_#{version}_Darwin_arm64.tar.gz"
      sha256 "5957dec3bcde9eea02af3ba2ffc367eb7833a80b107174da810f7f8f528efa4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/hone/releases/download/v#{version}/hone_#{version}_Linux_x86_64.tar.gz"
      sha256 "6477793f9ac232f2a9ca01b2ed7d7b9b92d253da78ab63f98cdc6ad902954793"
    end
    on_arm do
      url "https://github.com/thirdlf03/hone/releases/download/v#{version}/hone_#{version}_Linux_arm64.tar.gz"
      sha256 "1e17f76e57d45c7769a14cbb9b4ea4bcc843bdc2dbbb9b85ae37e35c9be42824"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hone"]
    end
  end

  caveats do
    "Shell completion:"
    ""
    "  # Bash"
    "  source <(hone completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(hone completion zsh)"
    ""
    "  # Fish"
    "  hone completion fish | source"
  end

  # No zap stanza required
end
