# This file was generated by GoReleaser. DO NOT EDIT.
cask "kire" do
  name "kire"
  desc "kire - Split long Markdown files at semantic boundaries"
  homepage "https://github.com/thirdlf03/kire"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kire"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_amd64.tar.gz"
      sha256 "d96694848f0afaa3b7c1909975f189a106f17a13a83430d1a61d57609ec3244d"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_arm64.tar.gz"
      sha256 "102c93901b2ac804f160731f4b69132f5dd449473381d744d7e7cfda767e3125"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_amd64.tar.gz"
      sha256 "7f7e6853b6474efa03f4fbd718170280c9e14796a4c1faa5301bf92515269db6"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_arm64.tar.gz"
      sha256 "9f0e741701391dbeb4342ec2cb8a4ac0ec11d33a74d6a88a375fc4afe60125ca"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kire"]
    end
  end

  caveats do
    "Shell completion を有効にするには:"
    ""
    "  # Bash"
    "  source <(kire completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(kire completion zsh)"
    ""
    "  # Fish"
    "  kire completion fish | source"
  end

  # No zap stanza required
end
