# This file was generated by GoReleaser. DO NOT EDIT.
cask "kire" do
  name "kire"
  desc "kire - Split long Markdown files at semantic boundaries"
  homepage "https://github.com/thirdlf03/kire"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kire"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_amd64.tar.gz"
      sha256 "8ed781c3553da838214a89bd017da9531a1906e4a41a000e70721ffbfe4fc722"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_arm64.tar.gz"
      sha256 "c80eeda362e96ead9ccfc0e28de6e8279264677dd9cfc9bc95a38722b926e6b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_amd64.tar.gz"
      sha256 "7810c5fb1d9621933490c43b3f57fa9aea961122cbd413b9abc43417cb3e0676"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_arm64.tar.gz"
      sha256 "39150220130061df704525a6e4ca60d2bf4e21da932fe2a0301a49dae9d2f5b5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kire"]
    end
  end

  caveats do
    "Shell completion を有効にするには:"
    ""
    "  # Bash"
    "  source <(kire completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(kire completion zsh)"
    ""
    "  # Fish"
    "  kire completion fish | source"
  end

  # No zap stanza required
end
