# This file was generated by GoReleaser. DO NOT EDIT.
cask "kire" do
  name "kire"
  desc "kire - Split long Markdown files at semantic boundaries"
  homepage "https://github.com/thirdlf03/kire"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kire"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_amd64.tar.gz"
      sha256 "5bbd1bb23bf5be89b9f5a5e52150ece6ffb326d2685a439c742fb69015a39dd6"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_darwin_arm64.tar.gz"
      sha256 "8db7225fb2c3e205b7f057134bc04af5860981e98649b949ead7b22d01f18491"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_amd64.tar.gz"
      sha256 "ae11efb4ccbc0b998c581c3a7ab05aa8f0ede1b4a6b213da0ff0a0b3fc04b172"
    end
    on_arm do
      url "https://github.com/thirdlf03/kire/releases/download/v#{version}/kire_#{version}_linux_arm64.tar.gz"
      sha256 "21a8f8cb2e4ca30ec1548e5a1d09dae928186309b2bb7a34f87e2fe29bbdbbf1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kire"]
    end
  end

  caveats do
    "Shell completion を有効にするには:"
    ""
    "  # Bash"
    "  source <(kire completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(kire completion zsh)"
    ""
    "  # Fish"
    "  kire completion fish | source"
  end

  # No zap stanza required
end
