# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-tdd" do
  name "spec-tdd"
  desc "Spec-driven TDD workflow CLI"
  homepage "https://github.com/thirdlf03/spec-tdd"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-tdd"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_x86_64.tar.gz"
      sha256 "cac105efddc33596ccd590541dcc42ac4147f37d2bf5fdb9553b2ea7d216c52c"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_arm64.tar.gz"
      sha256 "2cfaaef71026c104bfd7f8fb1a00ae930b1924345de58ed6bca84a401d9e3ea4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_x86_64.tar.gz"
      sha256 "89e759a12205a52efc9144d20a8115bc77ee7cde3f5a4f5a61108b22870ef631"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_arm64.tar.gz"
      sha256 "3757e9085ab3ad44a1fbe31b77f7ff0edfc6647e33b627432e6f86dfd8b650c2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spec-tdd"]
    end
  end

  caveats do
    "Shell completion:"
    ""
    "  # Bash"
    "  source <(spec-tdd completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(spec-tdd completion zsh)"
    ""
    "  # Fish"
    "  spec-tdd completion fish | source"
  end

  # No zap stanza required
end
