# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-tdd" do
  name "spec-tdd"
  desc "Spec-driven TDD workflow CLI"
  homepage "https://github.com/thirdlf03/spec-tdd"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-tdd"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_x86_64.tar.gz"
      sha256 "84fa1d5050411c261646f7fab11cb085061cc6a7f601e089c9fd63b6a3c5d104"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_arm64.tar.gz"
      sha256 "12e57b1b72e966ef545d107710fec7fd3ee53e00ec96a27caa582b8d14ff2101"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_x86_64.tar.gz"
      sha256 "ba7c3a394add92b6fde8bb7ac7d24a67b3111f6e765d39e83a6782cea42fbd5d"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_arm64.tar.gz"
      sha256 "d113daec2435c2b81fc9c742a564a1e3543d54d6d79dcc32e2a2484795f21893"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spec-tdd"]
    end
  end

  caveats do
    "Shell completion:"
    ""
    "  # Bash"
    "  source <(spec-tdd completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(spec-tdd completion zsh)"
    ""
    "  # Fish"
    "  spec-tdd completion fish | source"
  end

  # No zap stanza required
end
