# This file was generated by GoReleaser. DO NOT EDIT.
cask "spec-tdd" do
  name "spec-tdd"
  desc "Spec-driven TDD workflow CLI"
  homepage "https://github.com/thirdlf03/spec-tdd"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spec-tdd"

  on_macos do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_x86_64.tar.gz"
      sha256 "04a02edf24f823901b75774e45e3e8e355d5126cba1f0f15cfcb8d873d0f9208"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Darwin_arm64.tar.gz"
      sha256 "6e5c663a6dc2750b3ea2e6978bdc7fe5f33fc07a8993a4fe6d69747cf8a6307e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_x86_64.tar.gz"
      sha256 "ce82a1518bc140163b93fcc892493f3a91206c21ee890a4177a3a862c3c5a3a8"
    end
    on_arm do
      url "https://github.com/thirdlf03/spec-tdd/releases/download/v#{version}/spec-tdd_#{version}_Linux_arm64.tar.gz"
      sha256 "1ed05ceb7fcd85b4120269ef939b59b5432de1fa2c3313b1a92b87b1088b1d25"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spec-tdd"]
    end
  end

  caveats do
    "Shell completion:"
    ""
    "  # Bash"
    "  source <(spec-tdd completion bash)"
    ""
    "  # Zsh (add to .zshrc)"
    "  source <(spec-tdd completion zsh)"
    ""
    "  # Fish"
    "  spec-tdd completion fish | source"
  end

  # No zap stanza required
end
